# Brand style guide + voice source data. Rendered to .md and .pdf by build.py.
# Palettes were sampled from the actual logo files; voice was derived from the live sites,
# the 2023 "Texoma Campaign Concepts" deck (USP + brand attributes), and the hub's
# "The Most ___" property descriptors.

MASTER = {
    "usp": "The Best Lake Experience Close to Home",
    "attributes": ["Selling fun", "Broad choice of adventures", "Something for everyone", "Friendly staff / concierge",
                   "High-touch service", "Well-maintained properties", "Safe", "Experienced"],
    "personality": ["Fun", "Friendly", "Family", "Exciting", "Enjoyable", "Personable", "Accommodating", "Experienced", "Safe"],
    "campaign": "The Most Texoma",
}

BRANDS = [
  dict(
    slug="texoma-destinations", name="Texoma Destinations", kind="Hub / parent brand", domain="texomadestinations.com",
    tagline="The Most Texoma", most="The Most Texoma",
    logo="texoma-destinations/logo.png", hero="texoma-destinations/hero.jpg",
    positioning="The single place to plan and book everything on Lake Texoma — cabins, RV sites, glamping, boats, cruises, beach days and memberships — from a family of properties run by one local team. It's the best lake experience close to home, and only Texoma Destinations gives you the most of everything the lake has to offer.",
    audience="DFW-area families and friend groups within a 90-minute drive; repeat lake-goers; boat owners; groups planning reunions, retreats and weddings.",
    personality=["Fun", "Friendly", "Family-first", "Exciting", "Accommodating", "Experienced", "Safe"],
    voice=dict(
      summary="Confident host. Warm, plain-spoken, a little playful, never salesy. Talks like a local who knows every cove and wants you to have the best day possible.",
      do=["Lead with the experience, then the logistics ('Catch a sunset, then walk to your cabin').",
          "Use 'we' and 'you' — we are the people on the dock, not a booking engine.",
          "Say the specific thing: 'Friday and Saturday nights in season', not 'select dates'.",
          "Superlatives are earned and local: 'the most popular beach on Texoma', 'the only year-round fuel dock'.",
          "Close with a clear next step: Check availability · See cruise dates · Buy a day pass."],
      dont=["Corporate travel-speak ('accommodations', 'amenities' as a headline, 'world-class').",
            "Exclamation-point stacking or ALL CAPS urgency.",
            "Vague hedges ('may be available') — if it's not certain, don't publish it.",
            "Duplicating the same paragraph across properties."],
      words_use=["lake day", "close to home", "the most", "family", "cove", "sunset", "book", "check availability", "TAP members save"],
      words_avoid=["accommodations", "world-class", "luxurious (except Sundance)", "unforgettable", "getaway package deal", "click here"],
    ),
    palette=[("Texoma Blue", "#006cb4", "Primary — wordmark, buttons"), ("Lake Green", "#6cb43c", "Secondary — 'Destinations', accents"),
             ("Sun Gold", "#d8a83c", "Accent — circle mark, highlights"), ("Deep Navy", "#0c3c6c", "Text on light, TAP"),
             ("Sand", "#f5f1e8", "Backgrounds"), ("Ink", "#1a2233", "Body text")],
    type=dict(display="Big Noodle Titling (site) → web: Josefin Sans / Oswald caps", body="Source Sans 3 / Nunito", accent="Brittany Signature (script accents, sparingly)",
              notes="Wordmark is a bold geometric sans with a wave under TEXOMA. Headlines set in caps display faces; body in a friendly humanist sans."),
    logo_rules=["Primary lockup: TEXOMA (blue) over DESTINATIONS (green) with the wave. Use the circle mark for avatars/favicons.",
                "Minimum width 120 px / 1 inch. Clear space = height of the 'T' on all sides.",
                "On photos, place on a white or navy panel — never directly on busy water.",
                "Never recolor the green/blue split; one-color white and navy versions exist for dark and print."],
    photo=["Golden-hour water, families mid-activity (not posed), boats underway, real staff.",
           "Warm, slightly desaturated, horizon in the top third. Always show the lake.",
           "Texie the Dragon appears only in kids/family contexts."],
    messages=["One destination, more Texoma: every property, one account, one booking.",
              "Pay Now & Save — book online for the best rate.",
              "TAP: one membership, free day use, free ramps, discounts everywhere."],
    samples=dict(headline="The best lake experience close to home.", sub="Cabins, RV sites, glamping, boats, cruises and beach days — one lake, one booking.",
                 cta="Book your fun now", social="Friday-night dinner cruise, Saturday tritoon, Sunday hammock. That's the Most Texoma. Dates are live — link in bio.",
                 email="Your lake weekend is 90 minutes away"),
  ),

  dict(
    slug="lighthouse", name="Lighthouse Resort & Marina", kind="Resort · Marina · Fuel dock · Rentals · Events", domain="lighthouseresort.com",
    tagline="Lake Texoma's Family Fun Spot", most="The Most Exciting",
    logo="lighthouse/logo.png", hero="lighthouse/hero.jpg",
    positioning="The full-service, all-in-one lake resort: cabins for 1–16, waterfront RV sites, a working marina with the lake's year-round fuel dock, the newest rental fleet, covered slips, and the Lighthouse Lodge — all in Little Mineral near the dam, where the stripers are.",
    audience="Multi-generation families, anglers and guide clients, boat owners (slips), reunion and wedding planners, weekend renters from DFW.",
    personality=["Energetic", "Dependable", "Family-friendly", "Heritage (since the 1940s)", "Busy in a good way"],
    voice=dict(
      summary="The friendly harbormaster: knows boats, knows kids, keeps things moving. Proud of history without being nostalgic. Practical and upbeat.",
      do=["Talk in terms of a day: 'rent a tritoon at 9, fish till dark, walk to the cruise'.",
          "Name the heritage once per page: Preston Fishing Camp, 1944, the eight original Corps cabins.",
          "Be precise with marina facts — slip sizes, lease terms, fuel brand.",
          "Sell the convenience: everything is walkable."],
      dont=["Call it 'luxury' — it's comfortable, clean and fun.", "Bury the marina behind the resort or vice-versa; they're one place.",
            "Promise weather, water levels or fish."],
      words_use=["family fun", "marina", "fuel dock", "covered slips", "striper", "walk to", "Little Mineral", "year-round"],
      words_avoid=["luxury", "resort-style", "exclusive", "getaway"],
    ),
    palette=[("Lighthouse Navy", "#0c1854", "Primary — wordmark, header, footer"), ("Signal Red", "#e03c30", "Accent — CTA buttons, lighthouse stripes"),
             ("Harbor Blue", "#4aa3df", "Secondary accent, links"), ("Fog", "#f7f8fb", "Page background"), ("White", "#ffffff", "Cards, logo panel"), ("Ink", "#141a2e", "Body text")],
    type=dict(display="Lora (serif, 600–700)", body="Source Sans 3", accent="—",
              notes="The wordmark is a light humanist serif; Lora echoes it on the web. Serif headlines + sans body reads established and trustworthy."),
    logo_rules=["Lockup: circled lighthouse mark + 'Lighthouse' wordmark + 'RESORT & MARINA'. Mark-only version for small sizes.",
                "Always on a white panel when over photography (the site header uses a white chip on navy).",
                "Never stretch, never drop 'RESORT & MARINA' in first use; 'Lighthouse' alone is fine in running text.",
                "Red stripes are part of the mark — don't recolor."],
    photo=["Marina activity: boats fueling, tritoons leaving the dock, kids on the pier, the lighthouse at golden hour.",
           "Aerials of Little Mineral showing cabins + slips together.", "Avoid empty parking lots and off-season grey."],
    messages=["34 cabins, 1–16 guests, one-room to six-bedroom.", "Year-round fuel dock and the newest rental fleet on the lake.",
              "Month-to-month or prepaid slips — the only marina that offers both.", "Cruises leave from our dock."],
    samples=dict(headline="Lake Texoma's family fun spot.", sub="Cabins, waterfront RV sites, a marina that never closes for the season and the newest rental fleet on the water.",
                 cta="Check cabin availability", social="Fuel dock's open, tritoons are washed, stripers are schooling by the dam. Come make a day of it.",
                 email="Your cabin, your boat, your dock — all in one spot"),
  ),

  dict(
    slug="paradise", name="Paradise on Lake Texoma", kind="Glamping · Cabins · RV · Primitive camping", domain="paradisetexoma.com",
    tagline="this is Paradise", most="The Most Relaxing",
    logo="paradise/logo.png", hero="paradise/hero.jpg",
    positioning="Two hundred gated acres on the quiet western shore where you actually unplug: waterfront glamping Kabanas, Kasitas and Kimas, a 1920s train-car cabin, shaded RV loops that love vintage campers, primitive shoreline tents, a hammock garden and a community bar.",
    audience="Couples and young families seeking a slower weekend; glamping-curious first-timers; RV and vintage-camper owners; small reunions.",
    personality=["Laid-back", "Warm", "Whimsical", "Unhurried", "Neighborly"],
    voice=dict(
      summary="A friend who already has the fire going. Lowercase energy, sensory detail, gentle humor. Talks about marshmallows and sunsets before hookups and check-in.",
      do=["Write in lowercase-feeling sentences even when capitalized — short, soft, sensory.",
          "Use the property's own names: Kabana, Kasita, Kima, Paradise Express, hammock garden, community bar.",
          "Invite, don't instruct: 'claim a hammock' not 'hammocks are available'.",
          "Keep 'this is Paradise' as the signature line; the lowercase 'this is' is deliberate."],
      dont=["Hype or urgency — Paradise never shouts.", "Corporate campground language ('full-service RV resort').",
            "Over-promise privacy in the RV loops; be honest that glamping shares a bathhouse."],
      words_use=["kick your feet up", "unplug", "hammock", "sunset", "roast", "gated", "shade", "vintage camper", "this is Paradise"],
      words_avoid=["luxury", "resort", "amenities", "hurry", "limited time"],
    ),
    palette=[("Slate", "#5f7784", "Primary — PARADISE wordmark, buttons"), ("Lagoon", "#78b4c0", "Accent — wave, 'on Lake Texoma', CTAs"),
             ("Sage", "#b4d8c0", "Accent 2 — 'this'"), ("Driftwood", "#a8906c", "Accent — 'is'"), ("Linen", "#f6f3ec", "Page background"), ("Charcoal", "#2b333a", "Body text")],
    type=dict(display="Bebas Neue (condensed caps) for PARADISE-style headlines", body="Nunito", accent="Caveat (script) for 'this is'-style asides",
              notes="The wordmark stacks a script 'this is' over condensed caps PARADISE with a wave — recreate that rhythm: script kicker, condensed headline, rounded sans body."),
    logo_rules=["Full lockup 'this is PARADISE on Lake Texoma' is the primary mark. Never set 'This Is' in caps.",
                "Colors are muted by design — do not saturate. One-color white for dark photos.",
                "Minimum width 140 px. Clear space = height of 'is'.",
                "Google lists the property as 'Paradise Cove Resort & Camp' — brand copy always says 'Paradise on Lake Texoma'."],
    photo=["Hammocks, string lights, campfires, the train car, vintage campers, kids with sticks and marshmallows.",
           "Soft golden light, film-like grain, muted greens and blues. Wide, quiet compositions.", "Replace stock imagery (AdobeStock heroes on the old site) with real property photos."],
    messages=["Glamping three ways: Kabanas, Kasitas, Kimas.", "Sleep in a real 1920s train car.", "Vintage campers especially welcome.",
              "Hammock garden, community bar, one big fire."],
    samples=dict(headline="Kick your feet up. this is Paradise.", sub="Two hundred gated acres of oaks, hammocks and water views — and nothing on the schedule but the marshmallows.",
                 cta="See glamping & cabins", social="sunday–thursday nights are always discounted. the hammocks don't know what day it is either.",
                 email="the fire's already going"),
  ),

  dict(
    slug="sundance", name="Sundance Camp", kind="Tiny-cabin village · Group camp · Retreats", domain="sundancetexoma.com",
    tagline="Where rustic meets luxury", most="The Most Peaceful",
    logo="sundance/logo.png", hero="sundance/hero.jpg",
    positioning="Eighty private acres at the tip of Preston Point with seven themed tiny cabins, six wooded RV sites, primitive group camping and a 400-yard beach — a whole camp you take over for the people you actually want to be with. No Wi-Fi, by design.",
    audience="Corporate retreats, family reunions, scout/church groups, intimate weddings, couples who want dark skies.",
    personality=["Secluded", "Boutique", "Grounded", "Quietly luxurious", "Elemental"],
    voice=dict(
      summary="Calm, spare, a touch literary. Fewer words, longer pauses. Speaks to groups as hosts, to couples as confidants. The only brand that may say 'luxury' — always paired with 'rustic'.",
      do=["Short declarative lines. Let silence do work: 'The stars. Just — the stars.'",
          "Name the cabins (Pecos, Glorietta, Rosa Linda, Arroyo, Pinion House, Ponderosa, Cottonwood) — they're part of the charm.",
          "Sell the buy-out: 'your group, your lake, nobody else'.", "Be straightforward about no Wi-Fi and the shared bathhouse — it's a feature."],
      dont=["Party or family-fun energy — that's Lighthouse and Island View.", "Exclamation points.", "Over-decorate with adjectives; one good one per sentence."],
      words_use=["secluded", "disconnected on purpose", "tiny cabin village", "your group", "dark skies", "Preston Point", "chef-crafted", "concierge"],
      words_avoid=["fun spot", "party", "kids' paradise", "cheap", "campground (say camp)"],
    ),
    palette=[("Charcoal", "#2c2c36", "Primary — SUNDANCE wordmark, headers"), ("Sun Orange", "#f09c18", "Accent — sunburst, CTAs"),
             ("Dawn Yellow", "#f0d24a", "Accent 2 — highlights"), ("Bone", "#faf7f1", "Page background"), ("Oak", "#7a5a3a", "Secondary — wood tones in illustration"), ("Ink", "#1e1e26", "Body text")],
    type=dict(display="Josefin Sans (geometric caps, 600–700)", body="Lora (serif)", accent="—",
              notes="Wordmark is geometric caps under a sunburst-and-tree emblem. Caps headlines, serif body = rustic-luxury contrast."),
    logo_rules=["Square emblem (sun + tree) over SUNDANCE CAMP is the primary mark; emblem alone for avatars.",
                "Works on bone/white and on charcoal; orange never used as a background behind the emblem.",
                "Minimum 96 px square. Do not add taglines inside the lockup.",
                "Legacy site had no logo of its own (used the TD network mark) — always use the Sundance emblem now."],
    photo=["Blue-hour cabins with warm windows, star fields, empty beach at dawn, long tables under the pavilion, fire pits.",
           "Cool shadows, warm highlights; moody but not dark. Minimal people, or silhouettes.", "No inflatables, no crowds."],
    messages=["7 cabins, 6 RV sites, 80 acres, one group.", "Sleep 50+, host 100.", "No Wi-Fi. The night sky is the entertainment.", "Chef-crafted meals and concierge extras for groups."],
    samples=dict(headline="Where rustic meets luxury, and the lake meets the sky.", sub="Eighty acres, seven tiny cabins, one sandy beach and no one else around.",
                 cta="Book a tiny cabin", social="Seven cabins. One beach. Zero notifications. Sundance is open for fall retreats.",
                 email="Take the whole camp"),
  ),

  dict(
    slug="island-view", name="Island View Park", kind="Day-use beach · Shelters · Kayak & SUP rentals", domain="islandviewtexoma.com",
    tagline="Lake Texoma's most popular beach", most="The Most Fun",
    logo="island-view/logo.png", hero="island-view/hero.jpg",
    positioning="The day-trip beach for North Texas: real sand, a swim area, covered shelters with grills, volleyball, showers and kayaks — open 9 to sunset every day, $7 to get in, kids seven and under free.",
    audience="Day-trippers from Sherman/Denison/DFW, young families, birthday parties, church and youth groups, paddlers, TAP members.",
    personality=["Sunny", "Punchy", "Playful", "Straightforward", "Kid-friendly"],
    voice=dict(
      summary="The lifeguard-who-isn't (we have no lifeguard, and we say so): high energy, short sentences, price and hours up front. Rules are stated plainly and end with 'have fun'.",
      do=["Lead with price and hours — they're the whole decision.", "Use punchy fragments in headlines: 'Sand. Shade. Seven bucks.'",
          "Keep rules friendly and ALL-CAPS-free on the web (the sign at the gate can shout).", "Push 'buy your pass before you leave the house'."],
      dont=["Resort language — it's a park.", "Imply there's a lifeguard or a supervised swim area.", "Bury the no-glass rule."],
      words_use=["beach day", "sand", "day pass", "shelter", "9 to sunset", "kids 7 & under free", "buy ahead", "paddle"],
      words_avoid=["resort", "exclusive", "accommodations", "lifeguard on duty"],
    ),
    palette=[("Sky Blue", "#1f9fd0", "Primary — buttons, header accents"), ("Sunset Orange", "#f09018", "Accent — 'Island', sun, CTAs"),
             ("Sun Yellow", "#fcc00c", "Accent 2 — 'View', highlights"), ("Palm Green", "#6cb43c", "Accent 3 — palm, icons"), ("Sand", "#fffdf7", "Page background"), ("Ink", "#1c2a33", "Body text")],
    type=dict(display="Lilita One (rounded display)", body="Nunito (600–800)", accent="—",
              notes="The logo is a playful hand-lettered 'Island View' with sun, palm and wave. Lilita One carries that bounce; Nunito keeps it legible."),
    logo_rules=["Lockup: 'Island View' lettering + sun/palm + wave + 'DAY USE · PICNIC AREA · BEACH ACCESS'. Drop the descriptor line below 160 px.",
                "Bright colors are the brand; only use the one-color black version on print forms.",
                "Never place on orange or yellow backgrounds — white or sky blue only."],
    photo=["Sand, splashing kids, umbrellas, kayaks pulled up on the beach, shelters with a grill going. Midday bright and saturated.",
           "Show the crowd on holiday weekends — popularity is the pitch.", "Winter: eagles and empty sand for the 'year-round' story."],
    messages=["$7 day pass · kids 7 & under free · TAP members free.", "9am to sunset, every day, year-round.", "Shelters $40/day, reservation only.", "Kayaks and SUPs right off the beach."],
    samples=dict(headline="The beach day that's closer than you think.", sub="Lake Texoma's most popular sandy beach, open every day from 9am to sunset. Seven bucks gets you in.",
                 cta="Buy a day pass", social="Forecast says 94 and sunny. The sand says come early. Passes online — skip the gate line.",
                 email="Sand. Shade. Seven bucks."),
  ),

  dict(
    slug="fastrac", name="Fastrac Charters & Cruises", kind="Public cruises · Private charters · Lake tours · Water taxi", domain="fastrac.com",
    tagline="Catch a sunset. Catch some fun.", most="The Most Amazing",
    logo="fastrac/logo.png", hero="fastrac/hero.jpg",
    positioning="Lake Texoma's only cruise and charter service: ticketed sunset, dinner, lake-history and themed cruises nearly year-round; private charters for two to seventy on the Island Girl, Sight-Sea-Er II and Last Call; Lake Day beach trips; and the Texoma Water Taxi. Every boat has a USCG captain.",
    audience="Couples (date night, anniversaries), visiting friends and family, birders (eagle season), corporate groups, wedding parties, bachelorette groups.",
    personality=["Fun-loving", "Polished", "Confident captain", "Hospitable", "A little showy"],
    voice=dict(
      summary="The cruise director with a captain's license: playful superlatives, crisp logistics. Sells the moment (sunset, eagles, murder mystery) and then nails the details (boarding 15 minutes early, BYOB, 72-hour cancellation).",
      do=["Pair a hook with a fact: 'Texoma's largest party boat — 70 guests, climate-controlled, two decks.'",
          "Name the boats and give them personality.", "Use 'BYOB' proudly; it's a differentiator.", "Publish dates about a month out and say so."],
      dont=["Overuse 'Uber' — it belongs to the Water Taxi brand.", "Mix charter and public-cruise pricing in one sentence.", "Promise wildlife or weather."],
      words_use=["catch a sunset", "cruise", "charter", "captain & crew", "BYOB", "Island Girl", "Sight-Sea-Er II", "departs Lighthouse Marina", "Texoma's only"],
      words_avoid=["boat ride (that is a specific product)", "yacht party", "cheap", "ferry"],
    ),
    palette=[("Fastrac Navy", "#24306c", "Primary — FASTRAC wordmark, header"), ("Wake Cyan", "#48c0e4", "Accent — wave, CTAs"),
             ("Channel Blue", "#3078c0", "Secondary wave, links"), ("Mist", "#f5f8fc", "Page background"), ("White", "#ffffff", "Cards"), ("Ink", "#151b33", "Body text")],
    type=dict(display="Josefin Sans (300–600, wide tracking) — echoes the thin geometric FASTRAC letterforms", body="Inter", accent="—",
              notes="Wordmark: thin, widely spaced caps with an anchor for the T, 'CRUISES' beneath, two-tone wave. Headlines light-weight caps with generous tracking."),
    logo_rules=["Lockup 'FASTRAC CRUISES' with anchor + wave is primary. Legal/long form is 'Fastrac Charters & Cruises' in text.",
                "Boat-only square mark (anchor/boat) for avatars.", "White one-color on navy for hero overlays; never on cyan.",
                "Minimum width 160 px — the thin strokes disappear smaller."],
    photo=["Boats underway at golden hour, guests toasting on the top deck, eagles in bare winter trees, the Island Girl lit at dusk.",
           "Aerials showing the wake. Clean, bright, slightly cool blues.", "Themed cruises: costumes and table settings, not stock food."],
    messages=["Texoma's only cruise & charter service.", "Sunset $35 · Dinner $60 · Fri & Sat in season.", "Private charters for 2–70; captain, crew and fuel included.",
              "Eagle Watching Breakfast Cruises every winter."],
    samples=dict(headline="Catch a sunset. Catch some fun.", sub="Ticketed sunset and dinner cruises nearly year-round, private charters for two to seventy, and the water taxi to the islands.",
                 cta="See cruise dates & tickets", social="October dates just dropped: sunset cruises every Friday & Saturday, Murder Mystery on the 18th. BYOB, we bring the sunset.",
                 email="Your Friday night, on the water"),
  ),

  dict(
    slug="water-taxi", name="Texoma Water Taxi by Fastrac", kind="On-demand water taxi · Island shuttle", domain="texomawatertaxi.com",
    tagline="It's like Uber. On the water.", most="The Most Convenient",
    logo="fastrac/logo.png", hero="fastrac/boat-ride.jpg",
    positioning="Lake Texoma's only on-demand water taxi: $25 a person each way between Highport Marina and the islands, $100 an hour private for up to six, pickups at any marina or dock in the service area, sunrise to sunset — text and we're on the way.",
    audience="Boaters and island-goers around Highport, restaurant-goers, slip tenants, bachelorette/wedding groups, island campers.",
    personality=["Quick", "Casual", "Reliable", "No-nonsense", "Helpful"],
    voice=dict(
      summary="Text-message brevity. Rates, routes, phone number. The 'Uber on the water' line is the whole personality — keep the rest utilitarian and friendly.",
      do=["Put the phone/text number in every piece.", "State rates with the qualifiers ('each way', 'from the time we leave our dock').",
          "List destinations by name — people search for them.", "Say 'text us' before 'book online'."],
      dont=["Cruise-brand flourish — that's Fastrac.", "Hide surcharges (night $20, holiday $5/pp).", "Imply 24-hour service."],
      words_use=["like Uber, on the water", "text us", "pickup", "the islands", "each way", "sunrise to sunset", "your dock"],
      words_avoid=["cruise", "experience", "luxury", "ferry schedule"],
    ),
    palette=[("Night Navy", "#15213b", "Primary — header/footer"), ("Taxi Yellow", "#f2c230", "Accent — the Mellow Yellow, CTAs"),
             ("Wake Cyan", "#48c0e4", "Secondary — ties to Fastrac"), ("Cloud", "#f7f8fa", "Page background"), ("Ink", "#131a2a", "Body text")],
    type=dict(display="Oswald (500–700)", body="Inter", accent="—", notes="Sub-brand of Fastrac: uses the Fastrac lockup with 'Texoma Water Taxi by Fastrac' in text until a dedicated mark exists. Condensed display face = taxi-sign energy."),
    logo_rules=["Until a dedicated mark is designed, use the Fastrac lockup + 'Texoma Water Taxi' wordmark in Oswald.",
                "Yellow is the brand cue (the Mellow Yellow boat) — use it for buttons and the map pin, never for large text on white.",
                "Recommend: a simple taxi-check pattern + wave mark for boat livery and avatars."],
    photo=["The yellow boat at a dock, people stepping aboard with coolers, island drop-offs, the service-area map.", "Bright midday, candid, phone-camera OK for social."],
    messages=["$25 per person each way, Highport ↔ the islands.", "$100 an hour private, up to six.", "Text 903.414.6050 for a ride.", "Boat drop-offs, beverage runs, island camping."],
    samples=dict(headline="It's like Uber. On the water.", sub="A ride to the islands, a restaurant or back to your dock — without the swim.",
                 cta="Book a ride", social="Party Island is calling and your boat's at the ramp. Text 903-414-6050 — $25 a head from Highport.",
                 email="Need a ride to the island?"),
  ),

  dict(
    slug="tackle-box", name="Tackle Box Outfitters", kind="Bait & tackle · Licenses · Propane · Camp store", domain="tackleboxtexoma.com",
    tagline="Lake Texoma's fishing and outdoor headquarters", most="The Most Fishing",
    logo="tackle-box/logo.png", hero="tackle-box/hero.jpg",
    positioning="The last stop before the lake on SH 289: the only live-bait shop within 25 miles of Lighthouse, $12 Lake Texoma licenses, striper tackle the guides actually use, propane refills, ice, firewood and everything you forgot.",
    audience="Anglers (local and visiting), guide clients, RV campers heading to Lighthouse/Island View, weekenders stocking a cooler.",
    personality=["Salty", "Practical", "Local", "Dry humor", "Knows what's biting"],
    voice=dict(
      summary="The guy behind the counter: short, useful, a little gruff, secretly delighted to help. Talks in lists and tips. Never fancy.",
      do=["Lead with what's in stock and what's biting.", "Say '$12 license, both states' every time — it's the single best fact.",
          "Lists over paragraphs.", "Mention Bob Jr. the bass; people love him."],
      dont=["Retail hype ('huge selection!', 'unbeatable prices!').", "Long stories on the website — save them for the counter.", "Promise a bite."],
      words_use=["live bait", "shiners", "striper", "license", "propane", "last stop", "headquarters", "what's biting", "Bob Jr."],
      words_avoid=["boutique", "curated", "premium", "shop now (until the online store returns)"],
    ),
    palette=[("Black", "#111111", "Primary — wordmark, header"), ("Bobber Red", "#d8262c", "Accent — bobber, CTAs"),
             ("Bobber White", "#ffffff", "Cards, logo panel"), ("Canvas", "#f8f6f2", "Page background"), ("Line Yellow", "#f4b400", "Highlight (sparingly)"), ("Ink", "#161616", "Body text")],
    type=dict(display="Permanent Marker (hand-lettered) — headlines only, one per page", body="Barlow (400–700)", accent="—",
              notes="The logo is hand-drawn marker lettering with a red-and-white bobber for the 'o'. Keep the marker face for the H1 and use Barlow for everything else."),
    logo_rules=["Lockup 'the tackle box' with bobber 'o' is the only mark. Do not typeset the name in another font as a logo.",
                "Black on white or canvas; white one-color on black. Never on red.",
                "The bobber may be used alone as an icon/favicon."],
    photo=["Tackle walls, bait tanks, the mounts, hands holding a striper, the storefront at dawn with trucks and trailers.",
           "Natural light, slightly gritty; no stock fishing photos."],
    messages=["Only live bait within 25 miles of the Lighthouse.", "$12 Lake Texoma license — residents and non-residents.", "Propane: cylinders any time, RVs by appointment.", "Book a striper guide, buy your bait here."],
    samples=dict(headline="Everything you need for a day on the lake. One stop.", sub="Live bait, striper tackle, fishing licenses, propane, ice, firewood and cold drinks — on Highway 289 as you head to the water.",
                 cta="Find a fishing guide", social="Shiners in. Stripers schooling off the dam. $12 license at the counter. You know where we are.",
                 email="Shiners are in"),
  ),

  dict(
    slug="boaterwise", name="BoaterWise", kind="On-water boating instruction (NSBC certified)", domain="boaterwise.com",
    tagline="Your course to on-water confidence", most="The Most Confident",
    logo="boaterwise/logo.png", hero="lighthouse/boat-rental.jpg",
    positioning="Hands-on, small-group boat handling on Lake Texoma taught by NSBC-certified instructors who are also USCG captains. Four 3-hour modules to certification, private instruction on your own boat, and the Boat Club course — from the Lighthouse Marina dock.",
    audience="New boat owners, Big Water Boat Club members, renters who want confidence, spouses/teens learning to drive the family boat, experienced boaters polishing docking.",
    personality=["Encouraging", "Competent", "Safety-first", "Approachable", "Lightly humorous"],
    voice=dict(
      summary="A patient instructor who has seen every docking mistake and isn't judging. Clear, structured, confidence-building. Credentials stated once, then it's about you.",
      do=["Speak to the fear directly: docking in a crosswind, launching at a busy ramp.", "Be structured: modules, hours, class size, price.",
          "Credentials in one line: 'NSBC-certified instructors, USCG captains'.", "Tie to the family: Boat Club members train free; TAP Navigator saves 10%."],
      dont=["Lecture or use jargon without translating (S.C.A.N. → say what it is).", "Fear-based selling.", "Claim to be the Texas boater-education card course (it isn't)."],
      words_use=["confidence", "hands-on", "at the helm", "small group", "your boat", "certified", "captain", "module"],
      words_avoid=["school", "seminar", "classroom", "mandatory", "test"],
    ),
    palette=[("BoaterWise Blue", "#0054b4", "Primary — wordmark, buttons"), ("Horizon Blue", "#60a8fc", "Accent — tagline, highlights"),
             ("Life-Jacket Orange", "#ffb703", "Accent 2 — CTAs, safety callouts"), ("Spray", "#f4f8fd", "Page background"), ("Ink", "#0f1f38", "Body text")],
    type=dict(display="Exo 2 (600–800) — geometric, slightly technical like the wordmark", body="Inter", accent="—",
              notes="Wordmark: bold geometric caps with the A as a sail/triangle; light-blue tagline beneath. Captain's Crest emblem for certificates."),
    logo_rules=["Primary: 'BoaterWise' + tagline lockup. Tagline may be dropped under 200 px.", "White-except-A version for dark headers (exists).",
                "Captain's Crest emblem is for certificates, instructor apparel and the 'certified' badge — not a substitute logo.", "Remove `noindex` on the site; the brand is invisible to search today."],
    photo=["Student at the helm, instructor pointing, docking sequences, hands on the wheel; pontoons at the Lighthouse dock.",
           "Bright, clean, candid; show smiles and life jackets. No sunset glamour — this is daytime learning."],
    messages=["$199 per 3-hour module, 2–4 students.", "Instructors are NSBC certified and USCG captains.", "Complete all four modules for your Certificate of Completion.",
              "Private instruction on your own boat, up to 32 feet."],
    samples=dict(headline="Learn to run a boat the way captains do.", sub="Small-group, hands-on training on Lake Texoma with instructors who hold USCG captain's licenses.",
                 cta="Book a class", social="New boat? Congratulations. Now let's make the ramp boring. Module 1 & 2 dates open for October.",
                 email="Docking doesn't have to be the scary part"),
  ),

  dict(
    slug="tap", name="TAP — Texoma Access Package", kind="Annual membership program (hub-owned)", domain="texomadestinations.com/tap",
    tagline="One pass. The whole lake.", most="The Most Access",
    logo="tap/tap-pass.png", hero="tap/hero.jpg",
    positioning="One annual membership across every Texoma Destinations property: free day use at Island View and Paradise, free boat-ramp access at Lighthouse and Paradise, and 5–15% off stays, rentals, cruises, retail and fuel — Explorer $99, Adventurer $199, Navigator $399, plus the Big Water Boat Club tier.",
    audience="Locals and lake-house owners on the Preston Peninsula, frequent day-trippers, boat owners who launch often, Boat Club prospects.",
    personality=["Smart", "Generous", "Local-insider", "Clear", "Rewarding"],
    voice=dict(
      summary="The insider's deal explained by a friend who did the math. Benefit-led, tier-clear, never fine-print-first. Always 'members', never 'subscribers'.",
      do=["Do the math for them: 'pays for itself in two beach days and a boat launch'.", "Use the tier names consistently: Explorer / Adventurer / Navigator / Big Water Boat Club.",
          "Say 'TAP' on second reference; spell out 'Texoma Access Package' once.", "Every brand site links to /tap — TAP is the connective tissue."],
      dont=["Publish prices anywhere but the hub (they change).", "Use 'TAP Pass' as the product name (it's redundant) — 'TAP membership' or 'your TAP'.",
            "Carry legacy 'Individual/Family' plan language."],
      words_use=["members save", "free day use", "free ramp access", "TAP", "tier", "renews annually", "insider"],
      words_avoid=["subscription", "TAP Pass", "Annual Pass", "loyalty program"],
    ),
    palette=[("TAP Navy", "#0c3c6c", "Primary — card, headers"), ("Texoma Blue", "#006cb4", "Secondary — ties to hub"),
             ("Sun Gold", "#d8a83c", "Accent — Navigator tier, highlights"), ("Lake Green", "#6cb43c", "Explorer tier"), ("White", "#ffffff", "Card face")],
    type=dict(display="Josefin Sans / Oswald caps (inherits hub)", body="Source Sans 3", accent="—", notes="TAP is a hub product; typography follows the Texoma Destinations system with the navy card as its visual signature."),
    logo_rules=["The TAP card graphic (navy) is the visual identifier; the hub logo remains the brand.", "Tier badges: Explorer (green), Adventurer (blue), Navigator (gold), Boat Club (navy).",
                "If TAP becomes its own site, keep the card + hub colors so it reads as a Texoma Destinations program."],
    photo=["Members using benefits: launching at Lighthouse, walking into Island View, fueling up, boarding a cruise.", "Warm, candid, 'regulars' energy."],
    messages=["Free day use at Island View & Paradise.", "Free boat-ramp access at Lighthouse & Paradise.", "5–15% off stays, rentals, cruises, retail and fuel.", "From $99 a year."],
    samples=dict(headline="One pass. The whole lake.", sub="Free day use, free boat ramps and member pricing at every Texoma Destinations property — from $99 a year.",
                 cta="Compare TAP tiers", social="Two beach days + one boat launch = your TAP Explorer paid for. Everything after that is gravy.",
                 email="Your lake, on the house"),
  ),
]
