/**
 * BRAND REGISTRY — one entry per front door.
 * Facts here (addresses, phones) come from the hub's /companies directory, which we treat as
 * the system of record. Every value is mirrored in the facts registry (content/facts.json)
 * with a last-verified date so drift is visible.
 */
import type { BrandConfig, BrandSlug } from "./types";

const gf = (families: string) =>
  `https://fonts.googleapis.com/css2?${families}&display=swap`;

export const BRANDS: Record<BrandSlug, BrandConfig> = {
  /* ---------------------------------------------------------------------- */
  lighthouse: {
    slug: "lighthouse",
    domains: ["lighthouseresort.com", "www.lighthouseresort.com", "lighthouse.localhost"],
    canonicalDomain: "lighthouseresort.com",
    tagline: "Lake Texoma's Family Fun Spot",
    mostTag: "The Most Exciting",
    theme: {
      primary: "#0c1854",
      primaryDark: "#070f38",
      accent: "#e03c30",
      accent2: "#4aa3df",
      bg: "#f7f8fb",
      surface: "#ffffff",
      ink: "#141a2e",
      muted: "#5b647c",
      fontDisplay: "Lora",
      fontBody: "Source Sans 3",
      fontHref: gf("family=Lora:wght@500;600;700&family=Source+Sans+3:wght@400;600;700"),
      radius: "soft",
      header: "dark",
    },
    logo: { src: "/brands/lighthouse.png", width: 702, height: 194 },
    nap: {
      legalName: "Cornerstone Marine Group, LP dba Lighthouse Resort & Marina",
      displayName: "Lighthouse Resort & Marina",
      shortName: "Lighthouse",
      streetAddress: "300 Lighthouse Drive",
      city: "Pottsboro",
      region: "TX",
      postalCode: "75076",
      phone: "903.361.5070",
      phoneE164: "+19033615070",
      altPhones: [
        { label: "Fuel Dock & Rentals", phone: "903.786.2250", phoneE164: "+19037862250" },
        { label: "Reservations (Texoma Destinations)", phone: "903.361.8500", phoneE164: "+19033618500" },
      ],
      email: "info@lighthouseresort.com",
      geo: { lat: 33.860666, lng: -96.662635 },
      googleMapsUrl: "https://www.google.com/maps/place/Lighthouse+Resort+%26+Marina",
      googlePlaceId: "ChIJFXA3G2CRTIYRSjf5qs2Ca0A",
      facebook: "https://facebook.com/lighthousetexoma",
      instagram: "https://instagram.com/texomadestinations",
      hours: ["Office & reservations: 9am–5pm daily (off-peak)", "Fuel dock & rentals: 9am–5pm daily (off-peak); extended summer hours"],
    },
    pages: ["home", "stay", "plan", "groups", "rules", "packages"],
    hubPropertySlug: "lighthouse",
    hubLocationSlug: "lighthouse",
    primaryIntent: "cabins",
    primaryLabel: "Check cabin availability",
    secondaryIntent: "boats",
    secondaryLabel: "Rent a tritoon",
    schemaType: "Resort",
  },

  /* ---------------------------------------------------------------------- */
  paradise: {
    slug: "paradise",
    domains: ["paradisetexoma.com", "www.paradisetexoma.com", "paradise.localhost"],
    canonicalDomain: "paradisetexoma.com",
    tagline: "this is Paradise — on Lake Texoma",
    mostTag: "The Most Relaxing",
    theme: {
      primary: "#5f7784",
      primaryDark: "#3f5260",
      accent: "#78b4c0",
      accent2: "#b4d8c0",
      bg: "#f6f3ec",
      surface: "#ffffff",
      ink: "#2b333a",
      muted: "#6b7680",
      fontDisplay: "Bebas Neue",
      fontBody: "Nunito",
      fontHref: gf("family=Bebas+Neue&family=Caveat:wght@500;600&family=Nunito:wght@400;600;700"),
      radius: "round",
      header: "light",
    },
    logo: { src: "/brands/paradise.png", width: 506, height: 182 },
    nap: {
      legalName: "Texoma Destinations, LLC dba Paradise on Lake Texoma",
      displayName: "Paradise on Lake Texoma",
      shortName: "Paradise",
      streetAddress: "503 Paradise Park Road",
      city: "Pottsboro",
      region: "TX",
      postalCode: "75076",
      phone: "903.419.1009",
      phoneE164: "+19034191009",
      altPhones: [{ label: "Reservations (Texoma Destinations)", phone: "903.361.8500", phoneE164: "+19033618500" }],
      smsLine: { label: "Gate code / guest text line", phone: "903.414.6050", phoneE164: "+19034146050" },
      geo: { lat: 33.7948778, lng: -96.7871514 },
      googleMapsUrl: "https://www.google.com/maps/place/Paradise+Cove+Resort+%26+Camp/@33.795484,-96.785531,13z",
      googlePlaceId: "ChIJmxDwC3vtTIYRBBjuaHpwXx0",
      facebook: "https://facebook.com/paradisetexoma",
      instagram: "https://instagram.com/paradisetexoma",
      hours: ["Check-in 3pm · Check-out 11am", "Day use 9am–sunset (TAP members & day-pass guests)"],
    },
    pages: ["home", "stay", "plan", "groups", "rules", "packages"],
    hubPropertySlug: "paradise",
    hubLocationSlug: "paradise",
    primaryIntent: "cabins",
    primaryLabel: "See glamping & cabins",
    secondaryIntent: "rv",
    secondaryLabel: "Find an RV site",
    schemaType: "Campground",
  },

  /* ---------------------------------------------------------------------- */
  sundance: {
    slug: "sundance",
    domains: ["sundancetexoma.com", "www.sundancetexoma.com", "sundance.localhost"],
    canonicalDomain: "sundancetexoma.com",
    tagline: "Where rustic meets luxury",
    mostTag: "The Most Peaceful",
    theme: {
      primary: "#2c2c36",
      primaryDark: "#15151c",
      accent: "#f09c18",
      accent2: "#f0d24a",
      bg: "#faf7f1",
      surface: "#ffffff",
      ink: "#1e1e26",
      muted: "#6c6a66",
      fontDisplay: "Josefin Sans",
      fontBody: "Lora",
      fontHref: gf("family=Josefin+Sans:wght@600;700&family=Lora:ital,wght@0,400;0,500;1,400"),
      radius: "sharp",
      header: "dark",
    },
    logo: { src: "/brands/sundance.png", width: 612, height: 612 },
    nap: {
      legalName: "Texoma Destinations, LLC dba Sundance Camp",
      displayName: "Sundance Camp",
      shortName: "Sundance",
      streetAddress: "295 Glen Eden Drive",
      city: "Pottsboro",
      region: "TX",
      postalCode: "75076",
      phone: "903.419.1011",
      phoneE164: "+19034191011",
      altPhones: [{ label: "Reservations (Texoma Destinations)", phone: "903.361.8500", phoneE164: "+19033618500" }],
      geo: { lat: 33.8784503, lng: -96.6363588 },
      googleMapsUrl: "https://goo.gl/maps/7raH3tg6LpHN5yai7",
      googlePlaceId: "ChIJ_fGSOzGRTIYRoVhxEhLtAW8",
      facebook: "https://facebook.com/sundancetexoma",
      instagram: "https://instagram.com/sundancetexoma",
      hours: ["Check-in 3pm · Check-out 11am", "Registered overnight guests only"],
    },
    pages: ["home", "stay", "plan", "groups", "rules", "packages"],
    hubPropertySlug: "sundance",
    hubLocationSlug: "sundance",
    primaryIntent: "cabins",
    primaryLabel: "Book a tiny cabin",
    secondaryIntent: "events",
    secondaryLabel: "Plan a group retreat",
    schemaType: "Campground",
  },

  /* ---------------------------------------------------------------------- */
  "island-view": {
    slug: "island-view",
    domains: ["islandviewtexoma.com", "www.islandviewtexoma.com", "islandview.localhost"],
    canonicalDomain: "islandviewtexoma.com",
    tagline: "Lake Texoma's most popular beach",
    mostTag: "The Most Fun",
    theme: {
      primary: "#1f9fd0",
      primaryDark: "#136f93",
      accent: "#f09018",
      accent2: "#fcc00c",
      bg: "#fffdf7",
      surface: "#ffffff",
      ink: "#1c2a33",
      muted: "#5f6d78",
      fontDisplay: "Lilita One",
      fontBody: "Nunito",
      fontHref: gf("family=Lilita+One&family=Nunito:wght@400;600;700;800"),
      radius: "round",
      header: "light",
    },
    logo: { src: "/brands/island-view.png", width: 300, height: 150 },
    nap: {
      legalName: "Texoma Destinations, LLC dba Island View Park",
      displayName: "Island View Park",
      shortName: "Island View",
      streetAddress: "87426 Preston Bend Rd",
      city: "Pottsboro",
      region: "TX",
      postalCode: "75076",
      phone: "903.419.1008",
      phoneE164: "+19034191008",
      altPhones: [{ label: "Texoma Destinations", phone: "903.361.8500", phoneE164: "+19033618500" }],
      email: "info@islandviewtexoma.com",
      geo: { lat: 33.8594498, lng: -96.67116 },
      googleMapsUrl: "https://www.google.com/maps/place/87426+Preston+Bend+Rd%2C+Pottsboro%2C+TX+75076",
      googlePlaceId: "ChIJ073apd2TTIYR2N8yOjqBCg4",
      facebook: "https://facebook.com/islandviewtexoma",
      hours: ["Open daily 9am to sunset, year-round", "Gate closes 30 minutes after sunset"],
    },
    pages: ["home", "stay", "plan", "rules", "packages"],
    hubPropertySlug: "island-view",
    hubLocationSlug: "islandview",
    primaryIntent: "day-pass-cart",
    primaryLabel: "Buy a day pass",
    secondaryIntent: "kayaks",
    secondaryLabel: "Reserve kayaks & SUPs",
    schemaType: "Beach",
  },

  /* ---------------------------------------------------------------------- */
  fastrac: {
    slug: "fastrac",
    domains: ["fastrac.com", "www.fastrac.com", "fastrac.localhost"],
    canonicalDomain: "fastrac.com",
    tagline: "Lake Texoma's cruise, charter & tour service",
    mostTag: "The Most Amazing",
    theme: {
      primary: "#24306c",
      primaryDark: "#151d48",
      accent: "#48c0e4",
      accent2: "#3078c0",
      bg: "#f5f8fc",
      surface: "#ffffff",
      ink: "#151b33",
      muted: "#5a6480",
      fontDisplay: "Josefin Sans",
      fontBody: "Inter",
      fontHref: gf("family=Josefin+Sans:wght@300;400;600&family=Inter:wght@400;500;600;700"),
      radius: "soft",
      header: "dark",
    },
    logo: { src: "/brands/fastrac.png", width: 1500, height: 493 },
    nap: {
      legalName: "Texoma Destinations, LLC dba Fastrac Charters and Cruises",
      displayName: "Fastrac Charters & Cruises",
      shortName: "Fastrac",
      streetAddress: "300 Lighthouse Drive, Suite B (Charter Dock at Lighthouse Marina)",
      city: "Pottsboro",
      region: "TX",
      postalCode: "75076",
      phone: "903.361.0775",
      phoneE164: "+19033610775",
      altPhones: [
        { label: "Private charter quotes", phone: "903.200.1408", phoneE164: "+19032001408" },
        { label: "Texoma Destinations", phone: "903.361.8500", phoneE164: "+19033618500" },
      ],
      smsLine: { label: "Water taxi text line", phone: "903.414.6050", phoneE164: "+19034146050" },
      geo: { lat: 33.858662, lng: -96.661691 },
      googleMapsUrl: "https://goo.gl/maps/wvksdupFzYA2",
      googlePlaceId: "ChIJnaMTG1iSTIYRXUTXmkTMjXY",
      facebook: "https://www.facebook.com/fastraccruises",
      instagram: "https://www.instagram.com/fastraccruises/",
      hours: ["Public cruises Fri & Sat evenings in peak season (May–Sep); schedule posted about a month ahead", "Water taxi: sunrise to sunset"],
    },
    pages: ["home", "stay", "plan", "groups", "rules", "packages"],
    hubPropertySlug: "fastrac",
    hubLocationSlug: "fastrac",
    primaryIntent: "cruises",
    primaryLabel: "See cruise dates & tickets",
    secondaryIntent: "events",
    secondaryLabel: "Request a private charter",
    schemaType: "TouristAttraction",
  },

  /* ---------------------------------------------------------------------- */
  "tackle-box": {
    slug: "tackle-box",
    domains: ["tackleboxtexoma.com", "www.tackleboxtexoma.com", "tacklebox.localhost"],
    canonicalDomain: "tackleboxtexoma.com",
    tagline: "Lake Texoma's fishing & outdoor headquarters",
    mostTag: "The Most Fishing",
    theme: {
      primary: "#3b2417",
      primaryDark: "#21140e",
      accent: "#a63b2e",
      accent2: "#c49a50",
      bg: "#eee4cf",
      surface: "#f7f0df",
      ink: "#241b14",
      muted: "#6d6253",
      fontDisplay: "Roboto Slab",
      fontBody: "Barlow",
      fontHref: gf("family=Roboto+Slab:wght@600;700;800&family=Barlow:wght@400;500;600;700;800"),
      radius: "sharp",
      header: "dark",
    },
    logo: { src: "/brands/tackle-box.png", width: 300, height: 150 },
    nap: {
      legalName: "Tackle Box, LLC dba Tackle Box Outfitters",
      displayName: "Tackle Box Outfitters",
      shortName: "The Tackle Box",
      streetAddress: "83924 N State Hwy 289",
      city: "Pottsboro",
      region: "TX",
      postalCode: "75076",
      phone: "903.786.9010",
      phoneE164: "+19037869010",
      geo: { lat: 33.834293, lng: -96.678798 },
      googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=83924+N+State+Hwy+289,+Pottsboro,+TX+75076",
      googlePlaceId: "ChIJR8aUezOSTIYR4SBFbnMFwXA",
      facebook: "https://facebook.com/tackleboxoutfitters",
      hours: ["Store hours vary by season — shiners stocked year-round; call ahead for RV propane fills"],
    },
    pages: ["home"],
    hubPropertySlug: "the-tackle-box",
    hubLocationSlug: "tacklebox",
    primaryIntent: "fishing",
    primaryLabel: "Find a fishing guide",
    secondaryIntent: "tap",
    secondaryLabel: "Save 5–10% with TAP",
    schemaType: "SportingGoodsStore",
  },

  /* ---------------------------------------------------------------------- */
  boaterwise: {
    slug: "boaterwise",
    domains: ["boaterwise.com", "www.boaterwise.com", "boaterwise.localhost"],
    canonicalDomain: "boaterwise.com",
    tagline: "Your course to on-water safety",
    mostTag: "The Most Confident",
    theme: {
      primary: "#0054b4",
      primaryDark: "#003a80",
      accent: "#60a8fc",
      accent2: "#ffb703",
      bg: "#f4f8fd",
      surface: "#ffffff",
      ink: "#0f1f38",
      muted: "#56657d",
      fontDisplay: "Exo 2",
      fontBody: "Inter",
      fontHref: gf("family=Exo+2:wght@600;700;800&family=Inter:wght@400;500;600"),
      radius: "soft",
      header: "light",
    },
    logo: { src: "/brands/boaterwise.png", width: 2400, height: 544 },
    nap: {
      legalName: "Texoma Destinations, LLC dba BoaterWise",
      displayName: "BoaterWise",
      shortName: "BoaterWise",
      streetAddress: "Training dock: 300 Lighthouse Drive (Lighthouse Resort & Marina) · Office: 83924 N State Hwy 289",
      city: "Pottsboro",
      region: "TX",
      postalCode: "75076",
      phone: "903.361.0775",
      phoneE164: "+19033610775",
      geo: { lat: 33.860318, lng: -96.661881 },
      googleMapsUrl: "https://maps.app.goo.gl/wN7EgJjUXuCoed9T6",
      hours: ["Classes scheduled by appointment — book online"],
    },
    pages: ["home"],
    primaryIntent: "boaterwise-book",
    primaryLabel: "Book a class",
    secondaryIntent: "boaterwise-private",
    secondaryLabel: "Private instruction",
    schemaType: "EducationalOrganization",
  },

  /* ---------------------------------------------------------------------- */
  "water-taxi": {
    slug: "water-taxi",
    domains: ["texomawatertaxi.com", "www.texomawatertaxi.com", "watertaxi.localhost"],
    canonicalDomain: "texomawatertaxi.com",
    tagline: "It's like Uber… on the water",
    mostTag: "The Most Convenient",
    theme: {
      primary: "#15213b",
      primaryDark: "#0b1223",
      accent: "#f2c230",
      accent2: "#48c0e4",
      bg: "#f7f8fa",
      surface: "#ffffff",
      ink: "#131a2a",
      muted: "#5d6677",
      fontDisplay: "Oswald",
      fontBody: "Inter",
      fontHref: gf("family=Oswald:wght@500;600;700&family=Inter:wght@400;500;600"),
      radius: "soft",
      header: "dark",
    },
    logo: { src: "/brands/fastrac.png", width: 1500, height: 493 },
    nap: {
      legalName: "Texoma Destinations, LLC dba Fastrac Charters and Cruises (Texoma Water Taxi)",
      displayName: "Texoma Water Taxi by Fastrac",
      shortName: "Water Taxi",
      streetAddress: "Departs Lighthouse Marina, 300 Lighthouse Drive — pickups anywhere in the service area",
      city: "Pottsboro",
      region: "TX",
      postalCode: "75076",
      phone: "903.361.0775",
      phoneE164: "+19033610775",
      smsLine: { label: "Text for a ride", phone: "903.414.6050", phoneE164: "+19034146050" },
      geo: { lat: 33.858662, lng: -96.661691 },
      googleMapsUrl: "https://goo.gl/maps/wvksdupFzYA2",
      facebook: "https://www.facebook.com/fastraccruises",
      hours: ["Sunrise to sunset, on demand · Night trips by arrangement (surcharge applies)"],
    },
    pages: ["home", "plan", "rules"],
    hubPropertySlug: "fastrac",
    hubLocationSlug: "fastrac",
    primaryIntent: "water-taxi-book",
    primaryLabel: "Book a ride",
    secondaryIntent: "cruises",
    secondaryLabel: "See cruises & charters",
    schemaType: "TaxiService",
  },
};

export const BRAND_SLUGS = Object.keys(BRANDS) as BrandSlug[];

export function brandFromHost(host: string | null | undefined): BrandConfig | null {
  if (!host) return null;
  const h = host.toLowerCase().split(":")[0];
  for (const b of Object.values(BRANDS)) {
    if (b.domains.includes(h)) return b;
    // preview convenience: paradise.td-brand-sites.vercel.app, paradise.localhost
    if (h.startsWith(`${b.slug}.`) || h.startsWith(`${b.slug.replace("-", "")}.`)) return b;
  }
  return null;
}

export function isBrandSlug(s: string): s is BrandSlug {
  return (BRAND_SLUGS as string[]).includes(s);
}

/** Nav labels per page key (brand can override in content later if needed). */
export const PAGE_LABELS: Record<string, string> = {
  home: "Home",
  stay: "Stay & Experience",
  plan: "Plan Your Visit",
  groups: "Groups & Events",
  rules: "Rules & Policies",
  packages: "Packages & Events",
};

export const PAGE_PATHS: Record<string, string> = {
  home: "/",
  stay: "/stay",
  plan: "/plan-your-visit",
  groups: "/groups-and-events",
  rules: "/rules",
  packages: "/packages",
};

/** Per-brand nav label overrides where "Stay" isn't the right word. */
export const PAGE_LABEL_OVERRIDES: Partial<Record<BrandSlug, Partial<Record<string, string>>>> = {
  fastrac: { stay: "Cruises & Charters" },
  "island-view": { stay: "The Beach" },
  "tackle-box": { plan: "Visit the Store" },
  boaterwise: { plan: "Courses & Schedule", rules: "Policies" },
  "water-taxi": { plan: "Routes & Rates", rules: "Rider Policies" },
};
